update configure/makefile

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -16,8 +16,8 @@ if ! node -p 'process.exit(!(/v([0-9]+)/.exec(process.version)[1] >= 4))'; then
   exit 1
 fi
 
-if ! npm --version >/dev/null; then
-  echo 'Node Package Manager (npm) missing'
+if ! yarn --version >/dev/null; then
+  echo 'yarn missing'
   exit 1
 fi
 
